[build]
builder = "NIXPACKS"
buildCommand = "/opt/venv/bin/pip install poetry && /opt/venv/bin/poetry config virtualenvs.create false && /opt/venv/bin/poetry install --without dev --no-root"

[deploy]
startCommand = "bash start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
