[build]
builder = "NIXPACKS"
buildCommand = "pip install poetry && poetry config virtualenvs.create false && poetry install --no-dev --no-root"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
